# Practical_6: Numpy

In [ ]:
---

### Exercise 1:
Create a NumPy array of integers from 1 to 10.

```python
# Exercise 1
```

---

In [2]:
import numpy as np
np.arange(11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Exercise 2:
Create a 3x3 NumPy array filled with zeros.

```python
# Exercise 2
```


In [4]:
import numpy as np
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
a=np.zeros((3,3),dtype=np.int16)
a.dtype

dtype('int16')

### Exercise 3:
Create a NumPy array of 10 evenly spaced numbers between 0 and 5.

```python
# Exercise 3
```

In [5]:
n=np.linspace(0,5,10,endpoint=False)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

---

### Exercise 4:
Create a 5x5 identity matrix using NumPy.

```python
# Exercise 4
```

In [20]:
b=np.eye(5,5,dtype=np.int16)
b.dtype

dtype('int16')

---

### Exercise 5:
Create a 4x4 matrix with random values between 0 and 1.

```python
# Exercise 5
```

In [21]:
a=np.random.random((4,4))
a

array([[0.29742306, 0.89539058, 0.74183494, 0.51185917],
       [0.4854147 , 0.04510752, 0.3138969 , 0.76562033],
       [0.92077335, 0.99671405, 0.38186251, 0.66731973],
       [0.74380494, 0.89279644, 0.3937325 , 0.11344092]])

In [28]:
b=np.random.seed(10)
c=np.random.rand(4,4)
print(b)
print(c)

None
[[0.77132064 0.02075195 0.63364823 0.74880388]
 [0.49850701 0.22479665 0.19806286 0.76053071]
 [0.16911084 0.08833981 0.68535982 0.95339335]
 [0.00394827 0.51219226 0.81262096 0.61252607]]


In [33]:
w=np.random.seed(10)
print(w)

None


---

### Exercise 6:
Find the shape of a NumPy array.

```python
# Exercise 6
```

In [34]:
a.shape

(4, 4)

In [37]:
r=np.arange(16)
print(r)
r=r.reshape((4,4))
print(r)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


---

### Exercise 7:
Reshape a 1D NumPy array of 16 elements into a 4x4 matrix.

```python
# Exercise 7
```

In [66]:
a=np.arange(16)
x=a.reshape((4,4))
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


---

### Exercise 8:
Find the data type of the elements in a NumPy array.

```python
# Exercise 8
```

In [38]:
a.dtype

dtype('float64')

---

### Exercise 9:
Create a NumPy array of integers from 1 to 100 and find all even numbers in the array.

```python
# Exercise 9
```

In [48]:
ah=[x for x in np.arange(100) if x%2==0]
print(ah)
ab=numpy.array(ah)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98]


NameError: name 'numpy' is not defined

In [46]:
A=np.arange(2,101,2)
print(A)

[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


---

### Exercise 10:
Generate a 6x6 matrix of random integers between 10 and 50.

```python
# Exercise 10
```

In [52]:
a=np.random.randint(10,51,(6,6))
print(a)

[[32 21 22 38 42 25]
 [50 43 50 35 19 47]
 [10 28 33 13 39 26]
 [30 28 24 25 27 35]
 [27 42 27 26 36 22]
 [40 27 27 26 10 41]]


In [57]:
d=np.random.randint(10,50,(6,6))
print(d)
d.dtype

[[13 41 22 33 27 39]
 [15 30 15 16 26 20]
 [14 32 29 31 19 45]
 [45 21 28 29 27 20]
 [46 10 40 31 42 27]
 [23 13 41 42 42 48]]


dtype('int64')

---

### Exercise 11:
Slice a 2D NumPy array to extract a submatrix.

```python
# Exercise 11
```

In [76]:
a=np.arange(9)
print(a)
s=a.reshape(3,3)
print(s)
s[:,1:2]

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[1],
       [4],
       [7]])

---

### Exercise 12:
Calculate the sum of all elements in a NumPy array.

```python
# Exercise 12
```

In [83]:
c=np.arange(16)
print(c)
x=c.reshape((4,4))
print(x)
print(np.sum(x))
print(np.sum(x,axis=0))# sum column wisely
print(np.sum(x,axis=1))#sum rowisely

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
120
[24 28 32 36]
[ 6 22 38 54]


In [88]:
d=np.array([[3,5],[6,7]])
print(d)
print(np.sum(d))

[[3 5]
 [6 7]]
21


---

### Exercise 13:
Calculate the mean, median, and standard deviation of a NumPy array.

```python
# Exercise 13
```

In [94]:
print(d)
np.mean(d)



[[3 5]
 [6 7]]


5.25

In [95]:
np.median(d)

5.5

In [104]:
np.std(d)

1.479019945774904

---

### Exercise 14:
Find the maximum and minimum values in a NumPy array.

```python
# Exercise 14
```

In [107]:
print(d)

[[3 5]
 [6 7]]


In [105]:
np.max(d)

7

In [106]:
np.min(d)

3

---

### Exercise 15:
Create a NumPy array of 20 random integers and find the index of the maximum value.

```python
# Exercise 15
```

In [144]:
r=np.random.randint(20,size=(3,4))
print(r)

[[ 2 12 12 18]
 [14 13  2  5]
 [17 17  1 10]]


In [145]:
np.argmax(r)
print(F"index of maximum value is:{np.argmax(r)}")

index of maximum value is:3


---

### Exercise 16:
Create a NumPy array and reverse its elements.

```python
# Exercise 16
```

In [123]:
f=np.array([[1,2,3,5],[4,5,6,8]])
print(f)
f[::-1]

[[1 2 3 5]
 [4 5 6 8]]


array([[4, 5, 6, 8],
       [1, 2, 3, 5]])

---

### Exercise 17:
Create a 3x3 matrix and multiply it element-wise by another 3x3 matrix.

```python
# Exercise 17
```

In [157]:
d=np.array([[1,2,3],[4,5,6],[7,8,9]])
e=np.random.randint(9,size=(3,3))
print(e)
print(d)
print(np.multiply(d,e))

[[1 3 6]
 [3 1 0]
 [7 0 3]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  6 18]
 [12  5  0]
 [49  0 27]]


In [ ]:
---

### Exercise 18:
Create a diagonal matrix from a given 1D array.

```python
# Exercise 18
```

---

### Exercise 19:
Perform matrix multiplication on two 2D NumPy arrays.

```python
# Exercise 19
```

---

### Exercise 20:
Flatten a 2D NumPy array into a 1D array.

```python
# Exercise 20
```

---

### Exercise 21:
Stack two NumPy arrays vertically.

```python
# Exercise 21
```

---

### Exercise 22:
Stack two NumPy arrays horizontally.

```python
# Exercise 22
```

---

### Exercise 23:
Split a NumPy array into multiple sub-arrays.

```python
# Exercise 23
```

---

### Exercise 24:
Generate a random NumPy array and round each element to two decimal places.

```python
# Exercise 24
```

---

### Exercise 25:
Find the unique elements of a NumPy array.

```python
# Exercise 25
```

---

### Exercise 26:
Replace all elements in a NumPy array that are less than a specific value with that value.

```python
# Exercise 26
```

---

### Exercise 27:
Find the cumulative sum of the elements in a NumPy array.

```python
# Exercise 27
```

---

### Exercise 28:
Create a NumPy array and find the number of non-zero elements in it.

```python
# Exercise 28
```

---

### Exercise 29:
Create a NumPy array of random integers and sort it in ascending order.

```python
# Exercise 29
```

---

### Exercise 30:
Find the row-wise and column-wise sum of a 3x3 matrix.

```python
# Exercise 30
```

---

### Exercise 31:
Generate a 2D NumPy array with random values and normalize it (scale the values between 0 and 1).

```python
# Exercise 31
```

---

### Exercise 32:
Create two NumPy arrays and find the dot product.

```python
# Exercise 32
```

---

### Exercise 33:
Find the trace of a square NumPy matrix.

```python
# Exercise 33
```

---

### Exercise 34:
Create a 2D array and swap two rows.

```python
# Exercise 34
```

---

### Exercise 35:
Create a 1D NumPy array and convert it into a column vector.

```python
# Exercise 35
```

---

### Exercise 36:
Find the determinant of a 3x3 matrix.

```python
# Exercise 36
```

---

### Exercise 37:
Find the eigenvalues and eigenvectors of a 2x2 matrix.

```python
# Exercise 37
```

---

### Exercise 38:
Solve a system of linear equations using NumPy.

```python
# Exercise 38
```

---

### Exercise 39:
Add Gaussian noise to a NumPy array.

```python
# Exercise 39
```

---

### Exercise 40:
Create a 4x4 matrix and extract the diagonal elements.

```python
# Exercise 40
```

---

### Exercise 41:
Generate a NumPy array of 100 random values and clip the values to a range between 10 and 50.

```python
# Exercise 41
```

---

### Exercise 42:
Create a 2D NumPy array and replace all negative values with zero.

```python
# Exercise 42
```

---

### Exercise 43:
Find the inner and outer products of two NumPy arrays.

```python
# Exercise 43
```

---

### Exercise 44:
Calculate the pairwise distances between points in a NumPy array.

```python
# Exercise 44
```

---

### Exercise 45:
Create a structured NumPy array with fields for `name`, `age`, and `height`.

```python
# Exercise 45
```

---

### Exercise 46:
Create a 5x5 matrix of random integers and count the occurrences of each unique value.

```python
# Exercise 46
```

---

### Exercise 47:
Generate a random 3x3 NumPy array and subtract the mean of each row from the corresponding row.

```python
# Exercise 47
```

---

### Exercise 48:
Create a NumPy array of random integers and check if any of the values are greater than 50.

```python
# Exercise 48
```

---

### Exercise 49:
Calculate the moving average of a 1D NumPy array.

```python
# Exercise 49
```

---

### Exercise 50:
Find the Pearson correlation coefficient between two NumPy arrays.

```python
# Exercise 50
```

---

### Exercise 51:
Convert a NumPy array of radians to degrees.

```python
# Exercise 51
```

---

### Exercise 52:
Create a random NumPy array and compute its variance and standard deviation.

```python
# Exercise 52
```

---

### Exercise 53:
Create a 2D NumPy array and find the indices of the maximum values along each axis.

```python
# Exercise 53
```

---

### Exercise 54:
Compute the inverse of a 2x2 NumPy matrix.

```python
# Exercise 54
```

---

### Exercise 55:
Create a NumPy array of 10 random values and standardize it (mean 0, variance 1).

```python
# Exercise 55
```

---

### Exercise 56:
Perform element-wise addition and subtraction on two NumPy arrays.

```python
# Exercise 56
```

---

### Exercise 57:
Create a NumPy array of random values and find the maximum element's index.

```python
# Exercise 57
```

---

### Exercise 58:
Create a 3x3 NumPy array and rotate it by 90 degrees.

```python
# Exercise 58
```

---

### Exercise 59:
Compute the Frobenius norm of a matrix.

```python
# Exercise 59
```

---

### Exercise 60:
Create a 3D NumPy array and slice out a subarray.

```python
# Exercise 60
```

---