# Exercise 17
Exercise 17:
Create a 3x3 matrix and multiply it element-wise by another 3x3 matrix.

In [14]:
import numpy as np
d=np.random.randint(20,size=(3,3))
s=np.random.randint(10,size=(3,3))
print(s)
print(d)
print(np.multiply(d,s))


[[6 4 7]
 [6 2 6]
 [5 1 3]]
[[10 15  9]
 [ 6  4 17]
 [10  9  2]]
[[ 60  60  63]
 [ 36   8 102]
 [ 50   9   6]]


# Exercise 18:
Create a diagonal matrix from a given 1D array.


In [29]:
D=np.array([1,2,3])
A=np.diag(D)
print(A)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


# Exercise 19
Perform matrix multiplication on two 2D NumPy arrays.

In [46]:
f=np.random.randint(4,size=(2,2))
g=np.random.randint(8,size=(2,2))
print(f)
print(g)
mut=f*g
#print(mut)
print(np.multiply(f,g))

[[1 2]
 [0 1]]
[[5 2]
 [2 2]]
[[5 4]
 [0 2]]


# Exercise 20
Flatten a 2D NumPy array into a 1D array.

In [68]:
a=np.random.randint(4,size=(2,2))
print(a)
ar=a.flatten()
print(ar)

[[0 2]
 [0 1]]
[0 2 0 1]


# Exercise 21:
Stack two NumPy arrays vertically.

In [84]:
array1=np.array([1,2,3])
array2=np.array([3,4,5])
#stac=np.hstack((array1,array2))
stac2=np.vstack((array1,array2))
print(stac2)

[[1 2 3]
 [3 4 5]]


# Exercise 22:
Stack two NumPy arrays horizontally.

In [87]:
array1=np.array([1,2,3])
array2=np.array([3,4,5])
stac=np.hstack((array1,array2))
print(stac)

[1 2 3 3 4 5]


# Exercise 23:
Split a NumPy array into multiple sub-arrays.

In [112]:
n=np.arange(9)
sub=np.array_split(n,3)
print(sub)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


# Exercise 24:
Generate a random NumPy array and round each element to two decimal places.

In [132]:
dec=np.random.random(10)
s=print(np.round(dec,2))

[0.13 0.08 0.59 0.82 0.85 0.69 0.62 0.33 0.19 0.83]


# Exercise 25:
Find the unique elements of a NumPy array.

In [138]:
print(dec)
print(np.unique(dec))

[0.13080087 0.0830632  0.58942973 0.82058574 0.84971328 0.68752853
 0.62394085 0.32820548 0.19482824 0.83050848]
[0.0830632  0.13080087 0.19482824 0.32820548 0.58942973 0.62394085
 0.68752853 0.82058574 0.83050848 0.84971328]


# Exercise 26:
Replace all elements in a NumPy array that are less than a specific value 
with that value.

In [151]:
array=np.array([[1,2,4],[5,6,7]])
my_value=3
print(array)
print('---------------')
array[array<my_value]=my_value
print(array)

[[1 2 4]
 [5 6 7]]
---------------
[[3 3 4]
 [5 6 7]]


# Exercise 27:
Find the cumulative sum of the elements in a NumPy array.

In [156]:
np.sum(array,axis=0)

array([ 8,  9, 11])

# Exercise 28
Create a NumPy array and find the number of non-zero elements in it.

In [163]:
arr=np.array([[1,2,4,0],[1,0,5,8]])
print(np.count_nonzero(arr))

6


# Exercise 29:
Create a NumPy array of random integers and sort it in ascending order.

In [176]:
dfg=np.random.randint(20,size=(3,3))
print(dfg)
print("........................")
print(np.sort(dfg))

[[13  4 19]
 [10  8  9]
 [14 11 14]]
........................
[[ 4 13 19]
 [ 8  9 10]
 [11 14 14]]


In [184]:
h=np.sort(dfg)[::-1]
print(h)

[[11 14 14]
 [ 8  9 10]
 [ 4 13 19]]


# Exercise 30:
Find the row-wise and column-wise sum of a 3x3 matrix.

In [197]:
rand=np.random.randint(20,size=(3,3))
print(rand)
print("===================================")
print(np.sum(rand,axis=1)) ## for row wise
print("===================================")
print(np.sum(rand,axis=0))#column wise

[[18 13  7]
 [ 8  3 12]
 [ 0  6 19]]
[38 23 25]
[26 22 38]


# Exercise 31:
Generate a 2D NumPy array with random values and 
normalize it (scale the values between 0 and 1).

In [208]:
b=np.random.randint(7,size=(2,2))
print(b)
min_b=np.min(b)
max_b=np.max(b)
nom=(b-min_b)/(max_b-min_b)
print(nom)


[[3 2]
 [5 4]]
[[0.33333333 0.        ]
 [1.         0.66666667]]
